openapi: 3.1.0
info:
  title: Split Wise
  description: |-
    Swplit Wise
  version: 1.0.0
tags:
  - name: user
    description: user
paths:
  /users/{id}:
    get:
      tags:
        - user
      summary: Find user by identifier.
      description: Returns a single user
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
